### ISSUE TITLE
Rotate animation bug

### ISSUE THREAD

**Issue by exerty** [ryannair05/Cask-2#2]
When i have the new rotate animation on duscord gets messed up. The text gets kinda upside down but still not. The letters are the right way but the text is backwards and its read upside down
![AF676CE1-4962-4BE8-A576-2799D02B5857](https://user-images.githubusercontent.com/63980921/79700710-16f4c000-8298-11ea-8408-7bee74e2d24b.png)

**Comment by ryannair05** [comment]
This has now been fixed in Version 1.0.2.
