### ISSUE TITLE
Cask crashing issue with new update

### ISSUE THREAD

**Issue by ghost** [ryannair05/Cask-2#6]
When I updated to the new app version it made a couple daemons crash

**Comment by Healy1818** [comment]
Specifically with latest version of Cask 2 powerlogHelperd is continuously crashing for me.

**Comment by MakMak13** [comment]
Cask2 make My iPhone crash until few days, it was working well and Now jailbreack can’t be with This tweak.

**Comment by ryannair05** [comment]
Sorry about this, version 1.1.1 has been released to fix this bug.

**Comment by MakMak13** [comment]
Ok cool thank you, I love this tweak and happy to use again.

**Comment by MakMak13** [comment]
Still crashing for me (version 1.1.1) after installed tweak, respiring bug, and jailbreack not possible

**Comment by ryannair05** [comment]
Is there crashing, a respring bug, or both? Can you try disabling all other tweaks to see if that helps?

**Comment by Healy1818** [comment]
I am on iPhone 13.3.1 with checkra1n no longer having powerlog crash. I did not experience safe mode or resprings with Cask.

**Comment by MakMak13** [comment]
It began with a crash, I try a lot of time to jailbreack again but don’t work (reboot setting, use icleaner...) 
So I decided to delete all tweaks, and now I’m installing each by one, and after installing cask2 there is a respiring bug, and after that impossible to jailbreack, so I enter in safe mode, I delete cask2 and I can jailbreack.

**Comment by ryannair05** [comment]
This fixed the respring loop for someone else, try going to /var/mobile/Library/Preferences in filza and deleting com.ryannair05.caskprefs then install the latest version of Cask 2.

**Comment by MakMak13** [comment]
Done ! It’s works ! Thank you very much !
